services:
  app:
    build:
      context: .
    depends_on:
      - selenium
    env_file:
      - .env
    volumes:
      - .:/app
  selenium:
    image: seleniarm/standalone-chromium:4.8.3
    ports:
      - '5901:5900'
