version: '3.8'
services:
  app:
    build:
      context: .
    depends_on:
      - selenium
    env_file:
      - .env
    volumes:
      - .:/app
  selenium:
    image: seleniarm/standalone-chromium:4.0.0-20211111
    ports:
      - '5900:5900'
